services:
  - type: web
    name: quizapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn quizapp.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quizapp.settings
      - key: PYTHON_VERSION
        value: 3.11
