services:
  - type: web
    name: quizapp-django
    env: python
    buildCommand: ""
    startCommand: gunicorn quizapp.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quizapp.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your-secret-key-here
