services:
  - type: web
    name: quizapp-django
    env: python
    buildCommand: ""
    startCommand: gunicorn quizapp.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quizapp.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: django-insecure-upw1vx6dq&_c!4c649^83s%!b=pn7)f2@6q9u&*)ta@7$_l&kt
