services:
  - type: web
    name: quizapp-django
    env: python
    buildCommand: ""
    startCommand: gunicorn project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: PYTHON_VERSION
        value: 3.11
